### ISSUE TITLE
Need Converter for XML Version of OMM

### ISSUE THREAD

**Issue by TSKelso** [DigitalArsenal/spacedatastandards.org#3]
Needed for support for using OMM on CelesTrak.

**Comment by TJKoury** [comment]
I recommend we use the [CCSDS XML Spec](https://public.ccsds.org/Pubs/505x0b1.pdf), conforming to the [SANA XML Schemas](https://sanaregistry.org/r/ndmxml/).

**Comment by TJKoury** [comment]
[This commit](https://github.com/DigitalArsenal/spacedatastandards.org/commit/e9eabbb790a5fb7e250bb5953288c709a7ebe8e4) adds support for the XML message according to the spec.

Recommend reviewing the spec and seeing if a 'Comments' sub node is really needed under each section.  There are a lot of optional parts to the spec that should be reviewed (like optional attributes) due to the additional complexity / size they add without much contextual value.

**Comment by TJKoury** [comment]
Fixed a few formatting issues and added a `show null` option with [this commit](https://github.com/DigitalArsenal/spacedatastandards.org/commit/034792043939b362722240c8dbf960ee52741d37).

@TSKelso waiting on your review.
